// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUI
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1 - Use 'RecordedMethod1Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            HtmlEdit uIPasswordEdit = this.UIGmailInternetExploreWindow.UIGmailDocument.UIPasswordEdit;
            HtmlInputButton uISigninButton = this.UIGmailInternetExploreWindow.UIGmailDocument.UISigninButton;
            #endregion

            // Type '********' in 'Password' text box
            uIPasswordEdit.Password = this.RecordedMethod1Params.UIPasswordEditPassword;

            // Click 'Sign in' button
            Mouse.Click(uISigninButton, new Point(89, 29));
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public UIGmailInternetExploreWindow UIGmailInternetExploreWindow
        {
            get
            {
                if ((this.mUIGmailInternetExploreWindow == null))
                {
                    this.mUIGmailInternetExploreWindow = new UIGmailInternetExploreWindow();
                }
                return this.mUIGmailInternetExploreWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private UIGmailInternetExploreWindow mUIGmailInternetExploreWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditPassword = "gXNbzwVDiX4eXyb+IS72lg==";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIGmailInternetExploreWindow : BrowserWindow
    {
        
        public UIGmailInternetExploreWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Gmail";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Gmail");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIGmailDocument UIGmailDocument
        {
            get
            {
                if ((this.mUIGmailDocument == null))
                {
                    this.mUIGmailDocument = new UIGmailDocument(this);
                }
                return this.mUIGmailDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIGmailDocument mUIGmailDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIGmailDocument : HtmlDocument
    {
        
        public UIGmailDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Gmail";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/ServiceLogin";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://accounts.google.com/ServiceLogin?service=mail&continue=https://mail.googl" +
                "e.com/mail/#password";
            this.WindowTitles.Add("Gmail");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Passwd";
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Passwd";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Password";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Passwd\" id=\"Passwd\" type=\"password";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "50";
                    this.mUIPasswordEdit.WindowTitles.Add("Gmail");
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }
        
        public HtmlInputButton UISigninButton
        {
            get
            {
                if ((this.mUISigninButton == null))
                {
                    this.mUISigninButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUISigninButton.SearchProperties[HtmlButton.PropertyNames.Id] = "signIn";
                    this.mUISigninButton.SearchProperties[HtmlButton.PropertyNames.Name] = "signIn";
                    this.mUISigninButton.FilterProperties[HtmlButton.PropertyNames.DisplayText] = "Sign in";
                    this.mUISigninButton.FilterProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUISigninButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUISigninButton.FilterProperties[HtmlButton.PropertyNames.Class] = "rc-button rc-button-submit";
                    this.mUISigninButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "name=\"signIn\" class=\"rc-button rc-button";
                    this.mUISigninButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "50";
                    this.mUISigninButton.WindowTitles.Add("Gmail");
                    #endregion
                }
                return this.mUISigninButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIPasswordEdit;
        
        private HtmlInputButton mUISigninButton;
        #endregion
    }
}
